### ISSUE TITLE
[Yarn Start] Error "error:0308010C:digital envelope routines::unsupported" appears after running test

### ISSUE THREAD

**Issue by tarekselem** [epam/UUI#1008]
## Description
After running `yarn start` it throws this error:

`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/UUI/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/UUI/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/UUI/node_modules/webpack/lib/NormalModule.js:471:10)
    at /UUI/node_modules/webpack/lib/NormalModule.js:503:5
    at /UUI/node_modules/webpack/lib/NormalModule.js:358:12
    at /UUI/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/UUI/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/UUI/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

## Environment

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* UUI version:  4.9.2
* Browser name: Google Chrome Version 109.0.5414.87
* Operating System: macOS 13.1
* Node: 18.12.1

**Comment by AlekseyManetov** [comment]
closed according to https://github.com/epam/UUI/pull/1009#issuecomment-1413537350
