### ISSUE TITLE
[Rich Text Editor]: crash when trying to copy text from interface tables in UUI website

### ISSUE THREAD

**Issue by jakobz** [epam/UUI#2119]
## Prerequisites 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Steps to Reproduce

We have an RTE extension on UUI site, which allows embedding type ref tables with TS Interfaces into docs.

- open UUI web-site locally, which enabled RTE edit mode in docs
- open any page which contains RTE with properties tables
- select text in the table (e.g. type of prop)
- press CTRL+C, or copy via dropdown menu
- the app crashes. Stack trace:

```
Cannot read properties of null (reading 'setAttribute')
TypeError: Cannot read properties of null (reading 'setAttribute')
    at e.setFragmentData (webpack-internal:///../node_modules/slate-react/dist/index.es.js:4676:12)
    at editor.setFragmentData (webpack-internal:///../node_modules/@udecode/plate-table/dist/index.mjs:2383:7)
    at Object.setFragmentData (webpack-internal:///../node_modules/slate-react/dist/index.es.js:608:58)
    at eval (webpack-internal:///../node_modules/slate-react/dist/index.es.js:3709:21)
    at HTMLUnknownElement.callCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:3724:18)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:3768:20)
    at invokeGuardedCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:3825:35)
    at invokeGuardedCallbackAndCatchFirstError (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:3839:29)
    at executeDispatch (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:7982:7)
    at processDispatchQueueItemsInOrder (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:8008:11)
```

## Environment

* UUI version: latest development branch (Revision: 97b2e89781f9d13062e3abcb9e8142f0e7caf5ff, Date: 4/4/2024 6:55:38 PM)
* Browser name: Chrome 
* Operating System: Windows

**Comment by NatalliaAlieva** [comment]
Released in 5.8.0 ver.
