### ISSUE TITLE
The Next.js template is broken

### ISSUE THREAD

**Issue by vasilii-kovalev** [epam/UUI#814]
## Description

The Next.js template is broken because of the missing `@epam/uui` dependency.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the Next.js application using UUI template as described here: https://uui.epam.com/documents?id=gettingStarted#:~:text=Configuring%20from%20scratch%20for%20Next.js
2. Run `dev` script
3. Check console's (with the running script) output and/or http://localhost:3000/

## Actual result

```
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Users\Vasilii_Kovalev\Desktop\test2\.babelrc
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
error - ./node_modules/@epam/promo/index.js:8863:0
Module not found: Can't resolve '@epam/uui'       

Import trace for requested module:
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:        
https://nextjs.org/telemetry
```
![image](https://user-images.githubusercontent.com/10310491/200101713-cd38bd11-e5bc-4e40-9701-269bb8b3d34e.png)

After installing the latest version of `@epam/uui` library, I can see another issue:

```
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 2.2s (414 modules)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
wait  - compiling / (client and server)...
event - compiled client and server successfully in 204 ms (432 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 110 ms (433 modules)
ReferenceError: document is not defined
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1658:13
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1653:22
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1655:2
    at createCommonjsModule (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:728:35)
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1647:15
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:717:27
    at Object.<anonymous> (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:719:2)
    at Object.../node_modules/svg-sprite-loader/runtime/browser-sprite.build.js (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1719:30)
    at __webpack_require__ (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:21:30)
    at Object../icons/btn-cross-12.svg (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:7779:14)
error - ReferenceError: document is not defined
ReferenceError: document is not defined
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1658:13
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1653:22
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1655:2
    at createCommonjsModule (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:728:35)
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1647:15
    at C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:717:27
    at Object.<anonymous> (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:719:2)
    at Object.../node_modules/svg-sprite-loader/runtime/browser-sprite.build.js (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:1719:30)
    at __webpack_require__ (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:21:30)
    at Object../icons/btn-cross-12.svg (C:\Users\Vasilii_Kovalev\Desktop\test2\node_modules\@epam\promo\index.js:7779:14)
```
![image](https://user-images.githubusercontent.com/10310491/200102034-c6cac419-24e1-4b32-bd0c-55be0f6e6a1d.png)

## Expected result

The Next.js application is displayed and works without errors.

## Environment

* UUI version:
  * `@epam/promo`: latest (according to `package.json`)/4.4.0 (according to `yarn.lock`)
  * `@epam/uui-core`: latest (according to `package.json`)/4.9.0-rc.1 (according to `yarn.lock`)
  * `@epam/uui-components`: latest (according to `package.json`)/4.4.0 (according to `yarn.lock`)
  * `@epam/uui`: latest (4.9.0-rc.1), installed manually
* Operating System: Windows 10 64-bit

## Notes

According to the console's output, SWC is disabled because of the custom Babel config. Maybe it is time to get rid of it. Here's the [link to the documentation](https://nextjs.org/docs/advanced-features/compiler#why-swc).

**Comment by NatalliaAlieva** [comment]
Released in 4.10.0 version.
